# =============================================================================
# This script inspects the .npy files generated by the authors' pipeline.
#
# It prints the size of each file on disk, the shape and dtype of the NumPy
# array, and the structure of the Python object contained within (if applicable).
# =============================================================================

import os
from pathlib import Path
import numpy as np

# Directory containing the NumPy files generated by the authors' pipeline.
FIVE_FOLD_DIR = Path("../authors_code/battery_dataset_neurips23dataset_code/five_fold_utils")

def format_bytes(size):
    """Convert a size in bytes into a readable string."""
    if size < 1024:
        return f"{size} B"
    if size < 1024**2:
        return f"{size / 1024:.2f} KB"
    if size < 1024**3:
        return f"{size / 1024**2:.2f} MB"
    return f"{size / 1024**3:.2f} GB"

def inspect_file(file_path):
    print("=" * 70)
    print(f"FILE: {file_path.name}")
    print("=" * 70)

    # Size of the .npy file on disk.
    file_size = file_path.stat().st_size
    print(f"Dimensione su disco : {format_bytes(file_size)}")

    # Load the NumPy file.
    # allow_pickle=True is necessary because these files contain
    # Python objects (e.g. dictionaries).
    array = np.load(file_path, allow_pickle=True)

    print(f"Tipo restituito da np.load(): {type(array)}")
    print(f"Shape                  : {array.shape}")
    print(f"dtype                  : {array.dtype}")

    # The authors use .item() when loading these files, which means
    # the NumPy array contains one Python object.
    if array.shape == () and array.dtype == object:
        obj = array.item()

        print(f"Tipo dell'oggetto       : {type(obj)}")

        if isinstance(obj, dict):
            print(f"Numero di chiavi        : {len(obj)}")
            print(f"Chiavi                  : {list(obj.keys())}")

            for key, value in obj.items():
                print()
                print(f"--- Chiave: {key!r} ---")
                print(f"Tipo valore             : {type(value)}")

                if isinstance(value, (list, tuple)):
                    print(f"Lunghezza              : {len(value)}")

                    # Show only a few elements, without printing
                    # potentially huge objects.
                    if len(value) > 0:
                        print(f"Primi elementi         : {value[:5]}")

                elif isinstance(value, np.ndarray):
                    print(f"Shape                  : {value.shape}")
                    print(f"dtype                  : {value.dtype}")
                    print(f"Numero elementi        : {value.size}")

                else:
                    print(f"Valore                 : {value}")

        elif isinstance(obj, (list, tuple)):
            print(f"Lunghezza              : {len(obj)}")
            print(f"Primi elementi         : {obj[:5]}")

        else:
            print(f"Valore                 : {obj}")

    print()

def main():
    if not FIVE_FOLD_DIR.exists():
        print(f"ERRORE: directory non trovata: {FIVE_FOLD_DIR.resolve()}")
        print("Controlla il percorso FIVE_FOLD_DIR nello script.")
        return

    # These are the files we expect from the authors' pipeline.
    files = sorted(FIVE_FOLD_DIR.glob("*.npy"))

    if not files:
        print(f"Nessun file .npy trovato in: {FIVE_FOLD_DIR.resolve()}")
        return

    print(f"Directory analizzata: {FIVE_FOLD_DIR.resolve()}")
    print(f"File trovati: {len(files)}")
    print()

    for file_path in files:
        if file_path.name == "YOUR_all_car_dict.npz.npy": continue
        inspect_file(file_path)

if __name__ == "__main__":
    main()
